export const athleteProfile = {
  test: {
    name: "Current athlete state",
    date: "7 Oct 2026",
    clinic: "Working training estimate",
    analyser: "Running threshold capacity",
    note: "Working LT2 anchor adopted from the 7 Oct threshold session and half-marathon comparison; the 20 Aug lactate-test result remains the historical laboratory baseline.",
  },
  thresholds: [
    {
      key: "LT1",
      name: "Aerobic threshold",
      pace: "6:34/km",
      speed: "9.16 km/h",
      heartRate: "144 bpm",
      lactate: "~2.0 mmol/L",
      description: "Historical laboratory LT1 anchor. Continue to track pace-at-HR rather than moving this HR anchor without new evidence.",
    },
    {
      key: "LT2",
      name: "Anaerobic threshold",
      pace: "~4:55/km",
      speed: "~12.20 km/h",
      heartRate: "~167 bpm",
      lactate: "Working LT2 estimate",
      description: "Current working threshold centre. Practical threshold prescription: ~4:50–5:00/km with HR generally ~164–170 bpm; progress duration and control before pushing pace faster.",
    },
  ],
  zones: [
    { zone: "Z1", name: "Recovery", pace: "Use effort", heartRate: "≤141 bpm", share: "<85% LTHR" },
    { zone: "Z2", name: "Aerobic", pace: "Use effort", heartRate: "142–149 bpm", share: "85–89% LTHR" },
    { zone: "Z3", name: "Tempo", pace: "Use effort", heartRate: "150–157 bpm", share: "90–94% LTHR" },
    { zone: "Z4", name: "Sub-threshold", pace: "Use effort", heartRate: "158–166 bpm", share: "95–99% LTHR" },
    { zone: "Z5", name: "Threshold+", pace: "Use effort", heartRate: "167–203 bpm", share: "≥100% LTHR" },
  ],
  durability: {
    updated: "8 Oct 2026",
    model: "Race-derived durability model",
    basis: "Cheltenham Half Marathon + current running history",
    note: "Working sustainability estimates, not new lactate thresholds. Duration changes sharply within a zone, especially Z5; weather, hydration, fueling, terrain and fatigue can shorten these ranges.",
    raceEvidence: [
      { label: "Cheltenham Half", value: "1:45:47", detail: "Primary prolonged high-HR durability reference." },
      { label: "Average / peak HR", value: "176 / 186 bpm", detail: "Shows the race was sustained at a high cardiovascular load." },
      { label: "Above historical LT2", value: "~1:41:06", detail: "Time above the 20 Aug laboratory LT2 HR of 165 bpm." },
      { label: "Above LT2 + pace", value: "~1:17:56", detail: "Time above 165 bpm while also faster than the historical 5:17/km LT2 pace." },
      { label: "High-HR durability", value: "~80 min ≥174 bpm", detail: "Evidence that lower high-HR race bands are unusually durable for you." },
    ],
    zones: [
      { zone: "Z1", heartRate: "≤141 bpm", duration: "3–5+ h", confidence: "Medium", detail: "Very durable. Fueling, musculoskeletal fatigue and total time on feet are more likely to limit the effort than cardiovascular strain." },
      { zone: "Z2", heartRate: "142–149 bpm", duration: "2.5–4+ h", confidence: "Medium-high", detail: "Long-duration aerobic work. Master-plan long runs should progressively replace this estimate with observed personal durability." },
      { zone: "Z3", heartRate: "150–157 bpm", duration: "2–3+ h", confidence: "Medium-high", detail: "Steady aerobic/tempo durability. Cardiac drift becomes increasingly relevant, but this remains well below your demonstrated half-marathon cardiovascular load." },
      { zone: "Z4", heartRate: "158–166 bpm", duration: "1.5–2.5+ h", confidence: "High", detail: "Sub-threshold durability is strong. Your half-marathon evidence suggests the upper end is substantially more sustainable than generic zone-duration tables imply." },
      { zone: "Z5", heartRate: "167–203 bpm", duration: "Segmented below", confidence: "High for 167–184", detail: "This zone is too broad for one useful duration. Lower Z5 was sustained for a large part of the half marathon; the upper end behaves like severe/maximal work." },
    ],
    highHrBands: [
      { range: "167–174 bpm", duration: "~90–180 min", confidence: "High", detail: "Threshold-to-hard-race transition. Half-marathon evidence strongly supports prolonged durability here." },
      { range: "175–180 bpm", duration: "~75–100+ min", confidence: "High", detail: "Demonstrated hard-race durability. This is a major strength in your current profile." },
      { range: "181–184 bpm", duration: "~30–60 min", confidence: "Medium-high", detail: "Hard race / severe transition. Sustainable, but duration falls quickly as HR rises." },
      { range: "185–188 bpm", duration: "~5–20 min", confidence: "Medium", detail: "Severe race effort. Current evidence is much thinner than for the 175–184 bpm bands." },
      { range: "189–203 bpm", duration: "Seconds to ~10–15 min", confidence: "Low-medium", detail: "Not sufficiently established from the half marathon. Treat as high-intensity / finishing territory until more race data exists." },
    ],
    interpretation: "High-HR durability is a demonstrated strength. The athlete profile should track time-to-drift and observed duration at comparable pace/HR through the master plan so these estimates can be replaced by personal records.",
  },
  domains: [
    { name: "Moderate", range: "Below LT1", detail: "Slower than 6:34/km · typically below ~144 bpm" },
    { name: "Sub-threshold", range: "Z4", detail: "158–166 bpm · build controlled time near threshold without forcing pace" },
    { name: "Threshold", range: "Working LT2", detail: "~4:55/km at ~167 bpm · practical range 4:50–5:00/km and ~164–170 bpm" },
  ],
  personalBests: [
    { distance: "5K", value: "22:47", detail: "Cheltenham parkrun PB · 3 Oct 2026", source: "Run history" },
    { distance: "10K", value: "48:59", detail: "Fastest rolling 10K inside Cheltenham Half", source: "Current benchmark" },
    { distance: "Half", value: "1:30:00", detail: "Target · 21 Mar 2027", source: "Current goal" },
  ],
  progression: {
    currentPb: "22:47",
    currentDate: "3 Oct 2026",
    recentRate: "15–25 sec / 2 weeks",
    nextGate: "Sub-22:00",
    targetTime: "21:20",
    targetMeaning: "5K at 1:30 half-marathon pace equivalence",
    workingProjection: "~5 Dec 2026",
    caveat: "Linear planning hypothesis only. Improvement is expected to slow as performance rises.",
    actual: [
      { date: "2026-05-30", label: "30 May", result: "29:46", seconds: 1786 },
      { date: "2026-06-13", label: "13 Jun", result: "29:06", seconds: 1746 },
      { date: "2026-06-20", label: "20 Jun", result: "26:57", seconds: 1617 },
      { date: "2026-06-27", label: "27 Jun", result: "25:36", seconds: 1536 },
      { date: "2026-07-11", label: "11 Jul", result: "24:43", seconds: 1483 },
      { date: "2026-08-15", label: "15 Aug", result: "24:06", seconds: 1446 },
      { date: "2026-09-05", label: "5 Sep", result: "23:36", seconds: 1416 },
      { date: "2026-10-03", label: "3 Oct", result: "22:47", seconds: 1367 },
    ],
    projections: [
      {
        key: "fast",
        label: "Fast trend",
        rate: "25 sec / 2 weeks",
        crossing: "~21 Nov 2026",
        points: [
          { date: "2026-10-03", seconds: 1367 },
          { date: "2026-10-17", seconds: 1342 },
          { date: "2026-10-31", seconds: 1317 },
          { date: "2026-11-14", seconds: 1292 },
          { date: "2026-11-21", seconds: 1280 },
        ],
      },
      {
        key: "central",
        label: "Working trend",
        rate: "20 sec / 2 weeks",
        crossing: "~5 Dec 2026",
        points: [
          { date: "2026-10-03", seconds: 1367 },
          { date: "2026-10-17", seconds: 1347 },
          { date: "2026-10-31", seconds: 1327 },
          { date: "2026-11-14", seconds: 1307 },
          { date: "2026-11-28", seconds: 1287 },
          { date: "2026-12-05", seconds: 1280 },
        ],
      },
      {
        key: "slow",
        label: "Conservative trend",
        rate: "15 sec / 2 weeks",
        crossing: "~26 Dec 2026",
        points: [
          { date: "2026-10-03", seconds: 1367 },
          { date: "2026-10-17", seconds: 1352 },
          { date: "2026-10-31", seconds: 1337 },
          { date: "2026-11-14", seconds: 1322 },
          { date: "2026-11-28", seconds: 1307 },
          { date: "2026-12-12", seconds: 1292 },
          { date: "2026-12-26", seconds: 1280 },
        ],
      },
    ],
  },
  capacities: [
    { label: "Aerobic base", value: "70–80%", detail: "Training time below LT1; keep aerobic work controlled and track pace-at-HR improvement." },
    { label: "Threshold anchor", value: "4:55/km · 167 bpm", detail: "Working centre; use ~4:50–5:00/km and ~164–170 bpm for controlled threshold work." },
    { label: "Threshold progression", value: "Duration first", detail: "Extend controlled time near the new anchor before making threshold sessions systematically faster." },
    { label: "High intensity", value: "5–10%", detail: "Use above-threshold work sparingly for VO₂ max, 5K development and race-specific work." },
  ],
} as const;
